// <auto-generated />
using System;
using API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260214004122_UseTimeStampTzForDates")]
    partial class UseTimeStampTzForDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("API.Domain.Entities.Citation", b =>
                {
                    b.Property<int>("CiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cite_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CiteId"));

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("CiteId");

                    b.ToTable("citations", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.EtiquetteStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("step_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StepId"));

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    b.Property<int?>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("StepId");

                    b.HasIndex("ImageId");

                    b.HasIndex("TopicId", "StepOrder");

                    b.ToTable("etiquette_steps", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.EtiquetteTopic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopicId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("GlanceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("glance_order");

                    b.Property<int?>("GuideOrder")
                        .HasColumnType("integer")
                        .HasColumnName("guide_order");

                    b.Property<string>("IconKey")
                        .HasColumnType("text")
                        .HasColumnName("icon_key");

                    b.Property<string>("IconSet")
                        .HasColumnType("text")
                        .HasColumnName("icon_set");

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<bool>("ShowAsHighlight")
                        .HasColumnType("boolean")
                        .HasColumnName("show_as_highlight");

                    b.Property<bool>("ShowInGlance")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_glance");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TitleLong")
                        .HasColumnType("text")
                        .HasColumnName("title_long");

                    b.Property<string>("TitleShort")
                        .HasColumnType("text")
                        .HasColumnName("title_short");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TopicId");

                    b.HasIndex("ImageId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("etiquette_topics", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.EtiquetteTopicCitation", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<int>("CiteId")
                        .HasColumnType("integer")
                        .HasColumnName("cite_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("TopicId", "CiteId");

                    b.HasIndex("CiteId");

                    b.ToTable("etiquette_citations", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.Image", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImgId"));

                    b.Property<int?>("CiteId")
                        .HasColumnType("integer")
                        .HasColumnName("cite_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Desc")
                        .HasColumnType("text")
                        .HasColumnName("desc");

                    b.Property<string>("ImgSource")
                        .HasColumnType("text")
                        .HasColumnName("img_source");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ImgId");

                    b.HasIndex("CiteId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("API.Domain.Entities.EtiquetteStep", b =>
                {
                    b.HasOne("API.Domain.Entities.Image", "Image")
                        .WithMany("EtiquetteSteps")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("API.Domain.Entities.EtiquetteTopic", "Topic")
                        .WithMany("Steps")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("API.Domain.Entities.EtiquetteTopic", b =>
                {
                    b.HasOne("API.Domain.Entities.Image", "Image")
                        .WithMany("EtiquetteTopicsAsHero")
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("API.Domain.Entities.EtiquetteTopicCitation", b =>
                {
                    b.HasOne("API.Domain.Entities.Citation", "Citation")
                        .WithMany("EtiquetteTopicCitations")
                        .HasForeignKey("CiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("API.Domain.Entities.EtiquetteTopic", "Topic")
                        .WithMany("TopicCitations")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citation");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("API.Domain.Entities.Image", b =>
                {
                    b.HasOne("API.Domain.Entities.Citation", "Citation")
                        .WithMany("ImagesAttributed")
                        .HasForeignKey("CiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Citation");
                });

            modelBuilder.Entity("API.Domain.Entities.Citation", b =>
                {
                    b.Navigation("EtiquetteTopicCitations");

                    b.Navigation("ImagesAttributed");
                });

            modelBuilder.Entity("API.Domain.Entities.EtiquetteTopic", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("TopicCitations");
                });

            modelBuilder.Entity("API.Domain.Entities.Image", b =>
                {
                    b.Navigation("EtiquetteSteps");

                    b.Navigation("EtiquetteTopicsAsHero");
                });
#pragma warning restore 612, 618
        }
    }
}
