// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260403194540_AddShrineReviews")]
    partial class AddShrineReviews
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Citation", b =>
                {
                    b.Property<int>("CiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cite_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CiteId"));

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.Property<int?>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("CiteId");

                    b.ToTable("citations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EtiquetteStep", b =>
                {
                    b.Property<int>("StepId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("step_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StepId"));

                    b.Property<int?>("ImageId")
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    b.Property<int?>("StepOrder")
                        .HasColumnType("integer")
                        .HasColumnName("step_order");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.HasKey("StepId");

                    b.HasIndex("ImageId");

                    b.HasIndex("TopicId", "StepOrder");

                    b.ToTable("etiquette_steps", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EtiquetteTopic", b =>
                {
                    b.Property<int>("TopicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TopicId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("GlanceOrder")
                        .HasColumnType("integer")
                        .HasColumnName("glance_order");

                    b.Property<int?>("GuideOrder")
                        .HasColumnType("integer")
                        .HasColumnName("guide_order");

                    b.Property<string>("IconKey")
                        .HasColumnType("text")
                        .HasColumnName("icon_key");

                    b.Property<string>("IconSet")
                        .HasColumnType("text")
                        .HasColumnName("icon_set");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<bool>("ShowAsHighlight")
                        .HasColumnType("boolean")
                        .HasColumnName("show_as_highlight");

                    b.Property<bool>("ShowInGlance")
                        .HasColumnType("boolean")
                        .HasColumnName("show_in_glance");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("TitleLong")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("title_long");

                    b.Property<string>("TitleShort")
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("title_short");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TopicId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("etiquette_topics", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EtiquetteTopicCitation", b =>
                {
                    b.Property<int>("TopicId")
                        .HasColumnType("integer")
                        .HasColumnName("topic_id");

                    b.Property<int>("CiteId")
                        .HasColumnType("integer")
                        .HasColumnName("cite_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("TopicId", "CiteId");

                    b.HasIndex("CiteId");

                    b.ToTable("etiquette_citations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Folklore", b =>
                {
                    b.Property<int>("FolkloreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("folklore_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FolkloreId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("ImgId")
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    b.Property<string>("Information")
                        .HasColumnType("text")
                        .HasColumnName("information");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("ShrineId")
                        .HasColumnType("integer")
                        .HasColumnName("shrine_id");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("FolkloreId");

                    b.HasIndex("ImgId");

                    b.HasIndex("ShrineId");

                    b.ToTable("folklore", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FolkloreCitation", b =>
                {
                    b.Property<int>("FolkloreId")
                        .HasColumnType("integer")
                        .HasColumnName("folklore_id");

                    b.Property<int>("CiteId")
                        .HasColumnType("integer")
                        .HasColumnName("cite_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("FolkloreId", "CiteId");

                    b.HasIndex("CiteId");

                    b.ToTable("folklore_citations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.History", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly?>("EventDate")
                        .HasColumnType("date")
                        .HasColumnName("event_date");

                    b.Property<int?>("ImgId")
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    b.Property<string>("Information")
                        .HasColumnType("text")
                        .HasColumnName("information");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<int>("ShrineId")
                        .HasColumnType("integer")
                        .HasColumnName("shrine_id");

                    b.Property<int?>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("HistoryId");

                    b.HasIndex("ImgId");

                    b.HasIndex("ShrineId");

                    b.ToTable("history", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.HistoryCitation", b =>
                {
                    b.Property<int>("HistoryId")
                        .HasColumnType("integer")
                        .HasColumnName("history_id");

                    b.Property<int>("CiteId")
                        .HasColumnType("integer")
                        .HasColumnName("cite_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("HistoryId", "CiteId");

                    b.HasIndex("CiteId");

                    b.ToTable("history_citations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Image", b =>
                {
                    b.Property<int>("ImgId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ImgId"));

                    b.Property<int?>("CiteId")
                        .HasColumnType("integer")
                        .HasColumnName("cite_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Desc")
                        .HasColumnType("text")
                        .HasColumnName("desc");

                    b.Property<string>("ImgSource")
                        .HasColumnType("text")
                        .HasColumnName("img_source");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ImgId");

                    b.HasIndex("CiteId");

                    b.ToTable("images", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Kami", b =>
                {
                    b.Property<int>("KamiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("kami_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("KamiId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Desc")
                        .HasColumnType("text")
                        .HasColumnName("desc");

                    b.Property<int?>("ImgId")
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NameJp")
                        .HasColumnType("text")
                        .HasColumnName("name_jp");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("KamiId");

                    b.HasIndex("ImgId");

                    b.ToTable("kami", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.KamiCitation", b =>
                {
                    b.Property<int>("KamiId")
                        .HasColumnType("integer")
                        .HasColumnName("kami_id");

                    b.Property<int>("CiteId")
                        .HasColumnType("integer")
                        .HasColumnName("cite_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("KamiId", "CiteId");

                    b.HasIndex("CiteId");

                    b.ToTable("kami_citations", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("role_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasColumnName("name");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "User"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Editor"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Shrine", b =>
                {
                    b.Property<int>("ShrineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("shrine_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ShrineId"));

                    b.Property<string>("AddressRaw")
                        .HasColumnType("text")
                        .HasColumnName("address_raw");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .HasColumnType("text")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<int?>("ImgId")
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    b.Property<string>("InputtedId")
                        .HasColumnType("text")
                        .HasColumnName("inputted_id");

                    b.Property<decimal?>("Lat")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("lat");

                    b.Property<string>("Locality")
                        .HasColumnType("text")
                        .HasColumnName("locality");

                    b.Property<Point>("Location")
                        .HasColumnType("geography(point,4326)")
                        .HasColumnName("location");

                    b.Property<decimal?>("Lon")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("lon");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NameJp")
                        .HasColumnType("text")
                        .HasColumnName("name_jp");

                    b.Property<string>("Notes")
                        .HasMaxLength(10000)
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Prefecture")
                        .HasColumnType("text")
                        .HasColumnName("prefecture");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("ShrineDesc")
                        .HasColumnType("text")
                        .HasColumnName("shrine_desc");

                    b.Property<string>("Slug")
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Ward")
                        .HasColumnType("text")
                        .HasColumnName("ward");

                    b.Property<string>("Website")
                        .HasColumnType("text")
                        .HasColumnName("website");

                    b.HasKey("ShrineId");

                    b.HasIndex("ImgId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("slug IS NOT NULL");

                    b.ToTable("shrines", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ShrineGallery", b =>
                {
                    b.Property<int>("ShrineId")
                        .HasColumnType("integer")
                        .HasColumnName("shrine_id");

                    b.Property<int>("ImgId")
                        .HasColumnType("integer")
                        .HasColumnName("img_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ShrineId", "ImgId");

                    b.HasIndex("ImgId");

                    b.ToTable("shrine_gallery", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ShrineKami", b =>
                {
                    b.Property<int>("ShrineId")
                        .HasColumnType("integer")
                        .HasColumnName("shrine_id");

                    b.Property<int>("KamiId")
                        .HasColumnType("integer")
                        .HasColumnName("kami_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ShrineId", "KamiId");

                    b.HasIndex("KamiId");

                    b.ToTable("shrine_kami", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ShrineReview", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<int?>("ReviewedBy")
                        .HasColumnType("integer")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("ReviewerComment")
                        .HasColumnType("text")
                        .HasColumnName("reviewer_comment");

                    b.Property<int>("ShrineId")
                        .HasColumnType("integer")
                        .HasColumnName("shrine_id");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<int>("SubmittedBy")
                        .HasColumnType("integer")
                        .HasColumnName("submitted_by");

                    b.HasKey("ReviewId");

                    b.HasIndex("ReviewedBy");

                    b.HasIndex("ShrineId");

                    b.HasIndex("SubmittedBy");

                    b.ToTable("shrine_review", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ShrineTag", b =>
                {
                    b.Property<int>("ShrineId")
                        .HasColumnType("integer")
                        .HasColumnName("shrine_id");

                    b.Property<int>("TagId")
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("ShrineId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("shrine_tags", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tag_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TagId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("TitleEn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title_en");

                    b.Property<string>("TitleJp")
                        .HasColumnType("text")
                        .HasColumnName("title_jp");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("TagId");

                    b.HasIndex("TitleEn")
                        .IsUnique();

                    b.ToTable("tags", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PassHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pass_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("role_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.UserCollection", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.Property<int>("ShrineId")
                        .HasColumnType("integer")
                        .HasColumnName("shrine_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "ShrineId");

                    b.HasIndex("ShrineId");

                    b.ToTable("user_collection", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.EtiquetteStep", b =>
                {
                    b.HasOne("Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.EtiquetteTopic", "Topic")
                        .WithMany("Steps")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Domain.Entities.EtiquetteTopicCitation", b =>
                {
                    b.HasOne("Domain.Entities.Citation", "Citation")
                        .WithMany("EtiquetteTopicCitations")
                        .HasForeignKey("CiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.EtiquetteTopic", "Topic")
                        .WithMany("TopicCitations")
                        .HasForeignKey("TopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citation");

                    b.Navigation("Topic");
                });

            modelBuilder.Entity("Domain.Entities.Folklore", b =>
                {
                    b.HasOne("Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImgId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Shrine", "Shrine")
                        .WithMany("ShrineFolklores")
                        .HasForeignKey("ShrineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Shrine");
                });

            modelBuilder.Entity("Domain.Entities.FolkloreCitation", b =>
                {
                    b.HasOne("Domain.Entities.Citation", "Citation")
                        .WithMany("FolkloreCitations")
                        .HasForeignKey("CiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Folklore", "Folklore")
                        .WithMany("FolkloreCitations")
                        .HasForeignKey("FolkloreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citation");

                    b.Navigation("Folklore");
                });

            modelBuilder.Entity("Domain.Entities.History", b =>
                {
                    b.HasOne("Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImgId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Shrine", "Shrine")
                        .WithMany("ShrineHistories")
                        .HasForeignKey("ShrineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Shrine");
                });

            modelBuilder.Entity("Domain.Entities.HistoryCitation", b =>
                {
                    b.HasOne("Domain.Entities.Citation", "Citation")
                        .WithMany("HistoryCitations")
                        .HasForeignKey("CiteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.History", "History")
                        .WithMany("HistoryCitations")
                        .HasForeignKey("HistoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citation");

                    b.Navigation("History");
                });

            modelBuilder.Entity("Domain.Entities.Image", b =>
                {
                    b.HasOne("Domain.Entities.Citation", "Citation")
                        .WithMany("ImagesAttributed")
                        .HasForeignKey("CiteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Citation");
                });

            modelBuilder.Entity("Domain.Entities.Kami", b =>
                {
                    b.HasOne("Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImgId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Domain.Entities.KamiCitation", b =>
                {
                    b.HasOne("Domain.Entities.Citation", "Citation")
                        .WithMany("KamiCitations")
                        .HasForeignKey("CiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Kami", "Kami")
                        .WithMany("KamiCitations")
                        .HasForeignKey("KamiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Citation");

                    b.Navigation("Kami");
                });

            modelBuilder.Entity("Domain.Entities.RefreshToken", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Shrine", b =>
                {
                    b.HasOne("Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImgId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Domain.Entities.ShrineGallery", b =>
                {
                    b.HasOne("Domain.Entities.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImgId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Shrine", "Shrine")
                        .WithMany("ShrineGalleries")
                        .HasForeignKey("ShrineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Image");

                    b.Navigation("Shrine");
                });

            modelBuilder.Entity("Domain.Entities.ShrineKami", b =>
                {
                    b.HasOne("Domain.Entities.Kami", "Kami")
                        .WithMany("ShrineKamis")
                        .HasForeignKey("KamiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Shrine", "Shrine")
                        .WithMany("ShrineKamis")
                        .HasForeignKey("ShrineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kami");

                    b.Navigation("Shrine");
                });

            modelBuilder.Entity("Domain.Entities.ShrineReview", b =>
                {
                    b.HasOne("Domain.Entities.User", "ReviewedByUser")
                        .WithMany("ReviewedReviews")
                        .HasForeignKey("ReviewedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Shrine", "Shrine")
                        .WithMany("Reviews")
                        .HasForeignKey("ShrineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "SubmittedByUser")
                        .WithMany("SubmittedReviews")
                        .HasForeignKey("SubmittedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ReviewedByUser");

                    b.Navigation("Shrine");

                    b.Navigation("SubmittedByUser");
                });

            modelBuilder.Entity("Domain.Entities.ShrineTag", b =>
                {
                    b.HasOne("Domain.Entities.Shrine", "Shrine")
                        .WithMany("ShrineTags")
                        .HasForeignKey("ShrineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Tag", "Tag")
                        .WithMany("ShrineTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shrine");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Domain.Entities.UserCollection", b =>
                {
                    b.HasOne("Domain.Entities.Shrine", "Shrine")
                        .WithMany("UserCollections")
                        .HasForeignKey("ShrineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("UserCollections")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shrine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Citation", b =>
                {
                    b.Navigation("EtiquetteTopicCitations");

                    b.Navigation("FolkloreCitations");

                    b.Navigation("HistoryCitations");

                    b.Navigation("ImagesAttributed");

                    b.Navigation("KamiCitations");
                });

            modelBuilder.Entity("Domain.Entities.EtiquetteTopic", b =>
                {
                    b.Navigation("Steps");

                    b.Navigation("TopicCitations");
                });

            modelBuilder.Entity("Domain.Entities.Folklore", b =>
                {
                    b.Navigation("FolkloreCitations");
                });

            modelBuilder.Entity("Domain.Entities.History", b =>
                {
                    b.Navigation("HistoryCitations");
                });

            modelBuilder.Entity("Domain.Entities.Kami", b =>
                {
                    b.Navigation("KamiCitations");

                    b.Navigation("ShrineKamis");
                });

            modelBuilder.Entity("Domain.Entities.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Domain.Entities.Shrine", b =>
                {
                    b.Navigation("Reviews");

                    b.Navigation("ShrineFolklores");

                    b.Navigation("ShrineGalleries");

                    b.Navigation("ShrineHistories");

                    b.Navigation("ShrineKamis");

                    b.Navigation("ShrineTags");

                    b.Navigation("UserCollections");
                });

            modelBuilder.Entity("Domain.Entities.Tag", b =>
                {
                    b.Navigation("ShrineTags");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("ReviewedReviews");

                    b.Navigation("SubmittedReviews");

                    b.Navigation("UserCollections");
                });
#pragma warning restore 612, 618
        }
    }
}
